/**
 * The inventory, against the real service and real encryption.
 *
 * Every key in here is generated by the test. The publish state file this
 * machine actually holds is never read: it is the only copy of forty one
 * relics' republish rights, and a test that touched it could destroy them.
 * `RELIC_PUBLISH_STATE` points at a scratch directory for every case, which
 * also redirects the metadata cache, since the cache resolves beside it.
 */

import { afterEach, beforeEach, describe, expect, test } from 'bun:test';
import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import {
  encodeKey,
  encryptRelic,
  generateKey,
  generateRelicId,
  parseFragment,
} from '@relic/format';
import { MNEMONIC_WORDS, mnemonicToKey } from '@relic/format/mnemonic';
import { createApp, type RelicApp } from '@relic/server/src/app.ts';
import { MemoryStorage } from '@relic/server/src/storage.ts';
import { MemoryStore } from '@relic/server/src/store.ts';
import { listRelics, showRelic } from '../src/inventory.ts';
import { type FileReader, type PublishDeps, publish } from '../src/publish.ts';
import { republish } from '../src/republish.ts';
import {
  handleMessage,
  KEY_PHRASE_DISCLOSURE,
  LIST_TOOL_NAME,
  REPUBLISH_TOOL_NAME,
  SHOW_TOOL_NAME,
  TOOL_NAME,
} from '../src/server.ts';
import { publishStatePath } from '../src/state.ts';

const SERVICE = 'https://relic.example';
const DAY = 86_400_000;

let now = Date.parse('2026-08-20T12:00:00.000Z');
let scratch: string;
let storage: MemoryStorage;
let store: MemoryStore;
let app: RelicApp;
let disk: Map<string, Uint8Array>;
let deps: PublishDeps;

beforeEach(async () => {
  now = Date.parse('2026-08-20T12:00:00.000Z');
  scratch = await mkdtemp(join(tmpdir(), 'relic-inventory-'));
  process.env['RELIC_PUBLISH_STATE'] = join(scratch, 'publish-state.json');
  storage = new MemoryStorage();
  store = new MemoryStore();
  disk = new Map();
  app = createApp({
    store,
    storage,
    now: () => now,
    config: { serviceOrigin: SERVICE },
  });
  deps = {
    serviceOrigin: SERVICE,
    relicOrigin: SERVICE,
    files: fakeFiles(),
    fetch: shimFetch(),
    clientName: 'relic-mcp/inventory-test',
    identifySource: async (path) => ({
      identity: `realpath:${encodeURIComponent(path)}`,
      kind: 'realpath',
      path,
      description: path,
    }),
  };
});

afterEach(async () => {
  delete process.env['RELIC_PUBLISH_STATE'];
  await rm(scratch, { recursive: true, force: true });
});

function fakeFiles(): FileReader {
  return {
    resolve: (path) => (path.startsWith('/') ? path : `/work/${path}`),
    basename: (path) => path.slice(path.lastIndexOf('/') + 1),
    async stat(path) {
      const bytes = disk.get(path);
      if (bytes === undefined) return { kind: 'other' };
      return { kind: 'file', size: bytes.length };
    },
    async read(path) {
      const bytes = disk.get(path);
      if (bytes === undefined) throw new Error('ENOENT');
      return bytes;
    },
  };
}

/**
 * The real app for service URLs, and storage that honours a byte range.
 *
 * Range support is the point of one test: recovering a name reads the first
 * record rather than the whole relic, and a fake that ignored the header
 * would let a client that fetched megabytes pass.
 */
function shimFetch(): typeof globalThis.fetch {
  return (async (input: RequestInfo | URL, init?: RequestInit) => {
    const url = new URL(typeof input === 'string' ? input : String(input));

    if (url.origin === SERVICE) {
      const headers = new Headers(init?.headers);
      headers.set('x-forwarded-for', '198.51.100.10');
      return app.fetch(new Request(url.toString(), { ...init, headers }));
    }

    if (url.hostname === 'storage.invalid') {
      const key = url.pathname.replace(/^\/(?:upload|o)\//, '');
      if (init?.method === 'PUT') {
        storage.put(key, new Uint8Array(init.body as Uint8Array));
        return new Response(null, { status: 200 });
      }
      const bytes = await storage.read(key);
      if (bytes === undefined) return new Response(null, { status: 404 });

      const range = new Headers(init?.headers).get('range');
      const match = range?.match(/^bytes=(\d+)-(\d+)$/);
      if (match?.[1] !== undefined && match[2] !== undefined) {
        const start = Number(match[1]);
        const end = Math.min(Number(match[2]), bytes.length - 1);
        rangedFetches.push({ key, start, end });
        return new Response(
          bytes.slice(start, end + 1) as unknown as BodyInit,
          {
            status: 206,
          }
        );
      }
      return new Response(bytes as unknown as BodyInit, { status: 200 });
    }

    return new Response(null, { status: 404 });
  }) as typeof globalThis.fetch;
}

let rangedFetches: { key: string; start: number; end: number }[] = [];
beforeEach(() => {
  rangedFetches = [];
});

/** Publish through the real flow, so the envelope really holds the name. */
async function publishFile(name: string, body: string): Promise<string> {
  const path = `/work/${name}`;
  disk.set(path, new TextEncoder().encode(body));
  const result = await publish({ path }, deps);
  return result.relic_id;
}

/**
 * Seed a relic the way a client older than this one recorded it: a real
 * encrypted object on the service, and a state entry carrying only the three
 * fields that release wrote. No filename, no timestamp, no source, and no
 * entry in the source index, which is exactly the shape 32 of this machine's
 * 41 relics are in.
 */
async function seedLegacyRelic(options: {
  readonly filename: string;
  readonly body: string;
  readonly ttlDays?: number | undefined;
}): Promise<{ relicId: string; key: Uint8Array }> {
  const relicId = generateRelicId();
  const key = generateKey();
  const container = await encryptRelic({
    content: new TextEncoder().encode(options.body),
    filename: options.filename,
    mimetype: 'text/markdown',
    key,
  });

  await store.putRelic({
    id: relicId,
    publishIp: '198.51.100.10',
    grantedAt: now,
    expiresAt:
      options.ttlDays === undefined ? undefined : now + options.ttlDays * DAY,
    rendererClass: 'markdown',
    publishingClient: 'relic-mcp/old',
    declaredSizeBytes: options.body.length,
    version: 1,
    publishTokenHash: 'not-a-token-hash',
    publishedAt: now,
    objectLength: container.length,
    objectCrc32c: 'unused',
    mintsUsed: 0,
  });
  storage.put(relicId, container);

  await appendLegacyState(relicId, encodeKey(key));
  return { relicId, key };
}

/**
 * Write a state entry with only the fields the released client wrote.
 *
 * Written as raw JSON rather than through savePublishState, because the point
 * is to load a file this build never produced. The token is a synthetic
 * string; no publish token from anywhere real appears in this suite.
 */
async function appendLegacyState(
  relicId: string,
  encodedKey: string
): Promise<void> {
  const path = publishStatePath();
  let file: { relics: Record<string, unknown>; sources?: unknown } = {
    relics: {},
  };
  try {
    file = JSON.parse(await readFile(path, 'utf8')) as typeof file;
  } catch {
    // First entry; the file does not exist yet.
  }
  file.relics[relicId] = {
    key: encodedKey,
    publish_token: `synthetic-token-${relicId}`,
    version: 1,
  };
  await writeFile(path, JSON.stringify(file, null, 2));
}

async function callTool(
  name: string,
  args: Record<string, unknown>
): Promise<Record<string, unknown>> {
  const response = await handleMessage(
    {
      jsonrpc: '2.0',
      id: 1,
      method: 'tools/call',
      params: { name, arguments: args },
    },
    deps
  );
  return response?.result as Record<string, unknown>;
}

describe('relic_list enumerates what nothing else could', () => {
  test('lists every relic in a state file written by an older client', async () => {
    // The gap this closes: entries with no filename, no timestamp, and no
    // source are invisible to relic_lookup_source, which is the only other
    // way to find a relic id.
    const first = await seedLegacyRelic({
      filename: 'proposal.md',
      body: '# proposal\n',
    });
    const second = await seedLegacyRelic({
      filename: 'notes.md',
      body: '# notes\n',
    });
    const third = await seedLegacyRelic({
      filename: 'audit.md',
      body: '# audit\n',
    });

    const result = await listRelics({}, deps);

    expect(result.total).toBe(3);
    expect(result.count).toBe(3);
    expect(result.findable_by_source).toBe(0);
    expect(result.relics.map((row) => row.relic_id).sort()).toEqual(
      [first.relicId, second.relicId, third.relicId].sort()
    );
    for (const row of result.relics) {
      expect(row.source).toBeNull();
      expect(row.source_indexed).toBe(false);
      expect(row.published_at).toBeNull();
      expect(row.status).toBe('reachable');
    }
  });

  test('recovers the filename by decrypting a relic with no recorded source', async () => {
    const seeded = await seedLegacyRelic({
      filename: 'quarterly-review.md',
      body: '# quarterly review\n',
    });

    const result = await listRelics({}, deps);
    const row = result.relics[0];

    expect(row?.filename).toBe('quarterly-review.md');
    expect(row?.filename_basis).toBe('envelope');
    expect(row?.filename_unrecovered_reason).toBeNull();
    expect(row?.mimetype).toBe('text/markdown');
    expect(result.recovered_filenames).toBe(1);
    // Recovery reads the first record, not the object: a 40 MB relic costs
    // the same 64 KB as a small one.
    expect(rangedFetches).toEqual([
      { key: seeded.relicId, start: 0, end: 65_556 },
    ]);
  });

  test('caches a recovered name, so a second listing spends no opens', async () => {
    await seedLegacyRelic({ filename: 'report.md', body: '# report\n' });

    const first = await listRelics({}, deps);
    expect(first.opens_spent).toBe(1);
    expect(first.recovered_filenames).toBe(1);

    const second = await listRelics({}, deps);
    expect(second.opens_spent).toBe(0);
    expect(second.recovered_filenames).toBe(0);
    expect(second.relics[0]?.filename).toBe('report.md');
    expect(second.relics[0]?.filename_basis).toBe('cache');
    // The cheap check still ran, so the row is not a stale assertion that
    // the relic is fine.
    expect(second.relics[0]?.status).toBe('reachable');
    expect(second.relics[0]?.status_basis).toBe('record');
  });

  test('reports a removed relic as removed rather than dropping it', async () => {
    const alive = await seedLegacyRelic({
      filename: 'alive.md',
      body: '# alive\n',
    });
    const taken = await seedLegacyRelic({
      filename: 'taken-down.md',
      body: '# taken down\n',
    });

    await store.putTombstone({
      id: taken.relicId,
      publishIp: '198.51.100.10',
      publishedAt: now,
      publishingClient: 'relic-mcp/old',
      rendererClass: 'markdown',
      ciphertextHash: 'hash-of-record',
      deletedAt: now,
      operator: 'operator',
      reasonClass: 'abuse',
      reportReference: undefined,
    });

    const result = await listRelics({}, deps);

    expect(result.count).toBe(2);
    const removed = result.relics.find((row) => row.relic_id === taken.relicId);
    expect(removed?.status).toBe('removed');
    expect(removed?.status_detail).toContain('taken down');
    expect(removed?.filename).toBeNull();
    expect(removed?.filename_unrecovered_reason).toContain(
      'would not serve it'
    );
    expect(
      result.relics.find((row) => row.relic_id === alive.relicId)?.status
    ).toBe('reachable');
  });

  test('reports an expired relic as expired rather than dropping it', async () => {
    const seeded = await seedLegacyRelic({
      filename: 'ephemeral.md',
      body: '# ephemeral\n',
      ttlDays: 1,
    });
    now += 2 * DAY;

    const result = await listRelics({}, deps);

    expect(result.count).toBe(1);
    expect(result.relics[0]?.relic_id).toBe(seeded.relicId);
    expect(result.relics[0]?.status).toBe('expired');
    expect(result.relics[0]?.status_detail).toContain('lifetime');
  });

  test('a recorded lifetime that has run out beats the cheap check', async () => {
    // The unmetered check cannot see an expiry: the service's record outlives
    // the content, so it answers for an expired relic. A recorded lifetime is
    // what stops the row calling that relic reachable, and it costs nothing.
    disk.set('/work/short.md', new TextEncoder().encode('# short\n'));
    await publish({ path: '/work/short.md', ttl_days: 1 }, deps);
    now += 2 * DAY;

    const result = await listRelics({}, deps);

    expect(result.count).toBe(1);
    expect(result.opens_spent).toBe(0);
    expect(result.relics[0]?.status).toBe('expired');
    expect(result.relics[0]?.status_basis).toBe('local');
    expect(result.relics[0]?.expires_at_known).toBe(true);
    expect(result.relics[0]?.expires_at).not.toBeNull();
  });

  test('verify asks the service about a relic whose name is already known', async () => {
    await publishFile('known.md', '# known\n');

    const cheap = await listRelics({}, deps);
    expect(cheap.opens_spent).toBe(0);
    expect(cheap.relics[0]?.status_basis).toBe('record');

    const verified = await listRelics({ verify: true }, deps);
    expect(verified.opens_spent).toBe(1);
    expect(verified.relics[0]?.status_basis).toBe('mint');
    expect(verified.relics[0]?.status_detail).toContain('served version 1');
    // The recorded name still wins: verify is about the relic's state, not
    // about re-reading a name that cannot have changed.
    expect(verified.recovered_filenames).toBe(0);
    expect(verified.relics[0]?.filename_basis).toBe('recorded');
  });

  test('refresh re-reads the name from the relic itself', async () => {
    const seeded = await seedLegacyRelic({
      filename: 'original.md',
      body: '# original\n',
    });

    const first = await listRelics({}, deps);
    expect(first.recovered_filenames).toBe(1);

    const refreshed = await listRelics({ refresh: true }, deps);
    expect(refreshed.recovered_filenames).toBe(1);
    expect(refreshed.opens_spent).toBe(1);
    expect(refreshed.relics[0]?.filename).toBe('original.md');
    expect(refreshed.relics[0]?.filename_basis).toBe('envelope');
    expect(refreshed.relics[0]?.relic_id).toBe(seeded.relicId);
  });

  test('include_expired false reports the count it left out', async () => {
    await seedLegacyRelic({
      filename: 'ephemeral.md',
      body: '# gone\n',
      ttlDays: 1,
    });
    await seedLegacyRelic({ filename: 'kept.md', body: '# kept\n' });
    now += 2 * DAY;

    const result = await listRelics({ include_expired: false }, deps);

    expect(result.count).toBe(1);
    expect(result.total).toBe(2);
    expect(result.excluded_expired).toBe(1);
    expect(result.relics[0]?.filename).toBe('kept.md');
  });

  test('a service outage lists every relic with a reason, never an empty list', async () => {
    await seedLegacyRelic({ filename: 'one.md', body: '# one\n' });
    await seedLegacyRelic({ filename: 'two.md', body: '# two\n' });
    await seedLegacyRelic({ filename: 'three.md', body: '# three\n' });

    deps = {
      ...deps,
      // Through unknown because a stub that throws before reading its
      // arguments declares none, and fetch carries a `preconnect` member no
      // caller here touches.
      fetch: (async () => {
        throw new TypeError('fetch failed');
      }) as unknown as typeof globalThis.fetch,
    };

    const result = await listRelics({}, deps);

    expect(result.count).toBe(3);
    expect(result.total).toBe(3);
    expect(result.opens_spent).toBe(0);
    for (const row of result.relics) {
      expect(row.status).toBe('unreachable');
      expect(row.status_detail).toContain('could not be reached');
      // The one sentence that stops an outage reading as a graveyard.
      expect(row.status_detail).toContain(
        'says nothing about whether the relic is still there'
      );
      expect(row.filename).toBeNull();
      expect(row.filename_unrecovered_reason).toContain('would not serve it');
      // The link is still handed over: an outage does not lose the key.
      expect(row.share_url).toContain(`${SERVICE}/${row.relic_id}#r1`);
    }
  });

  test('a relic whose bytes are gone is not reported as reachable', async () => {
    const seeded = await seedLegacyRelic({
      filename: 'orphaned.md',
      body: '# orphaned\n',
    });
    await storage.delete(seeded.relicId);

    const result = await listRelics({}, deps);

    expect(result.count).toBe(1);
    // The service cannot tell vanished bytes from an upload still in flight
    // for a relic with no lifetime, so it reports the temporary one and this
    // client repeats it rather than inventing a stronger claim. What matters
    // is that the row does not read as a healthy relic.
    expect(result.relics[0]?.status).toBe('not_yet_published');
    expect(result.relics[0]?.status_detail).toContain('temporary');
    expect(result.relics[0]?.filename).toBeNull();
  });

  test('newest first, and a limit says how many were held back', async () => {
    const oldest = await publishFile('oldest.md', '# oldest\n');
    await publishFile('middle.md', '# middle\n');
    const newest = await publishFile('newest.md', '# newest\n');

    const all = await listRelics({}, deps);
    expect(all.relics.map((row) => row.filename)).toEqual([
      'newest.md',
      'middle.md',
      'oldest.md',
    ]);
    expect(all.truncated).toBe(false);
    expect(all.relics.at(-1)?.relic_id).toBe(oldest);
    expect(all.relics[0]?.relic_id).toBe(newest);

    const limited = await listRelics({ limit: 1 }, deps);
    expect(limited.count).toBe(1);
    expect(limited.total).toBe(3);
    expect(limited.truncated).toBe(true);
    expect(limited.relics[0]?.filename).toBe('newest.md');
  });

  test('a publish records the name, so listing it spends no opens at all', async () => {
    await publishFile('fresh.md', '# fresh\n');

    const result = await listRelics({}, deps);

    expect(result.opens_spent).toBe(0);
    expect(result.recovered_filenames).toBe(0);
    expect(result.relics[0]?.filename).toBe('fresh.md');
    expect(result.relics[0]?.filename_basis).toBe('recorded');
    expect(result.relics[0]?.published_at).not.toBeNull();
    expect(result.relics[0]?.expires_at_known).toBe(true);
    expect(result.relics[0]?.expires_at).toBeNull();
    expect(result.findable_by_source).toBe(1);
    expect(result.relics[0]?.source_indexed).toBe(true);
  });

  test('never puts a publish token in its output', async () => {
    await publishFile('fresh.md', '# fresh\n');
    await seedLegacyRelic({ filename: 'old.md', body: '# old\n' });

    const result = await callTool(LIST_TOOL_NAME, {});
    const serialized = JSON.stringify(result);
    const state = JSON.parse(await readFile(publishStatePath(), 'utf8')) as {
      relics: Record<string, { publish_token: string }>;
    };

    for (const entry of Object.values(state.relics)) {
      expect(serialized).not.toContain(entry.publish_token);
    }
    expect(serialized).not.toContain('publish_token');
    // The share URL is the disclosure the tool exists to make, and it is
    // named as a credential rather than presented as an identifier.
    expect(serialized).toContain('#r1');
    expect(serialized).toMatch(/decryption key/);
  });
});

describe('relic_show reads back what a link holds', () => {
  test('returns the current content, which is what makes a republish an edit', async () => {
    const relicId = await publishFile('plan.md', '# plan\n\nstep one\n');
    disk.set('/work/plan.md', new TextEncoder().encode('# plan\n\nstep two\n'));
    await republish({ relic_id: relicId, path: '/work/plan.md' }, deps);

    const shown = await showRelic(
      { relic_id: relicId, include_content: true },
      deps
    );

    expect(shown.content).toBe('# plan\n\nstep two\n');
    expect(shown.versions).toBe(2);
    expect(shown.version).toBe(2);
    expect(shown.filename).toBe('plan.md');
    expect(shown.renderer_class).toBe('markdown');
    expect(shown.content_omitted_reason).toBeNull();
    expect(shown.republish_call).toEqual({
      name: 'relic_republish',
      arguments: { relic_id: relicId, path: '/work/plan.md' },
    });
  });

  test('reads back a relic whose source was never recorded', async () => {
    const seeded = await seedLegacyRelic({
      filename: 'legacy.md',
      body: '# what this link holds\n',
    });

    const shown = await showRelic(
      { relic_id: seeded.relicId, include_content: true },
      deps
    );

    expect(shown.content).toBe('# what this link holds\n');
    expect(shown.filename).toBe('legacy.md');
    expect(shown.filename_basis).toBe('envelope');
    // No source path was ever recorded, so no call is invented for one.
    expect(shown.republish_call).toBeNull();
    expect(shown.share_url).toContain('#r1');
  });

  test('reports bytes that are not text as bytes, never as mangled text', async () => {
    const relicId = generateRelicId();
    const key = generateKey();
    const content = new Uint8Array([0x89, 0x50, 0x4e, 0x47, 0xff, 0xfe, 0x00]);
    const container = await encryptRelic({
      content,
      filename: 'chart.png',
      mimetype: 'image/png',
      key,
    });
    await store.putRelic({
      id: relicId,
      publishIp: '198.51.100.10',
      grantedAt: now,
      expiresAt: undefined,
      rendererClass: 'image',
      publishingClient: 'relic-mcp/old',
      declaredSizeBytes: content.length,
      version: 1,
      publishTokenHash: 'not-a-token-hash',
      publishedAt: now,
      objectLength: container.length,
      objectCrc32c: 'unused',
      mintsUsed: 0,
    });
    storage.put(relicId, container);
    await appendLegacyState(relicId, encodeKey(key));

    const shown = await showRelic(
      { relic_id: relicId, include_content: true },
      deps
    );

    expect(shown.content).toBeNull();
    expect(shown.content_omitted_reason).toContain('not valid UTF-8');
    expect(shown.content_bytes).toBe(content.length);
    expect(shown.filename).toBe('chart.png');
    expect(shown.mimetype).toBe('image/png');
  });

  test('a removed relic answers with the takedown, not a decrypt failure', async () => {
    const seeded = await seedLegacyRelic({
      filename: 'gone.md',
      body: '# gone\n',
    });
    await store.putTombstone({
      id: seeded.relicId,
      publishIp: '198.51.100.10',
      publishedAt: now,
      publishingClient: 'relic-mcp/old',
      rendererClass: 'markdown',
      ciphertextHash: 'hash-of-record',
      deletedAt: now,
      operator: 'operator',
      reasonClass: 'abuse',
      reportReference: undefined,
    });

    const shown = await showRelic(
      { relic_id: seeded.relicId, include_content: true },
      deps
    );

    expect(shown.status).toBe('removed');
    expect(shown.versions).toBeNull();
    expect(shown.content).toBeNull();
    expect(shown.content_omitted_reason).toContain('would not serve it');
  });

  test('refuses a relic this machine never published, without a round trip', async () => {
    const elsewhere = generateRelicId();
    let calls = 0;
    deps = {
      ...deps,
      fetch: (async (input: RequestInfo | URL, init?: RequestInit) => {
        calls += 1;
        return deps.fetch(input, init);
      }) as typeof globalThis.fetch,
    };

    await expect(showRelic({ relic_id: elsewhere }, deps)).rejects.toThrow(
      /published from another machine/
    );
    expect(calls).toBe(0);
  });

  test('the transcript names the republish path and the disclosure', async () => {
    const relicId = await publishFile('brief.md', '# brief\n');

    const result = await callTool(SHOW_TOOL_NAME, {
      relic_id: relicId,
      include_content: true,
    });
    const text = JSON.stringify(result['content']);

    expect(text).toContain('relic_republish');
    expect(text).toContain('every version it has ever held');
    expect(text).toContain('# brief');
    expect(text).toContain('key phrase:');
    expect(text).toContain(KEY_PHRASE_DISCLOSURE);
  });

  test('relic_show carries key_phrase and disclosure while relic_list does not', async () => {
    const relicId = await publishFile('memo.md', '# memo\n');

    const showResult = await callTool(SHOW_TOOL_NAME, {
      relic_id: relicId,
    });
    const showStructured = showResult['structuredContent'] as Record<
      string,
      unknown
    >;
    expect(typeof showStructured['key_phrase']).toBe('string');
    const showPhraseWords = (showStructured['key_phrase'] as string).split(' ');
    expect(showPhraseWords.length).toBe(MNEMONIC_WORDS);

    const shareUrl = showStructured['share_url'] as string;
    const fragment = shareUrl.split('#')[1] as string;
    const decodedKey = parseFragment(fragment).key;
    expect(mnemonicToKey(showPhraseWords)).toEqual(decodedKey);
    const listResult = await callTool(LIST_TOOL_NAME, {});
    const listStructured = listResult['structuredContent'] as {
      relics: Record<string, unknown>[];
    };
    expect(listStructured.relics.length).toBeGreaterThanOrEqual(1);
    for (const row of listStructured.relics) {
      expect(row['key_phrase']).toBeUndefined();
    }
    const listText = JSON.stringify(listResult['content']);
    expect(listText).not.toContain(KEY_PHRASE_DISCLOSURE);
  });

  test('publish and republish results carry key_phrase that round-trips to fragment key and carries disclosure', async () => {
    disk.set('/work/doc.md', new TextEncoder().encode('# doc\n'));
    const pubResult = await callTool(TOOL_NAME, {
      path: '/work/doc.md',
    });
    const pubStructured = pubResult['structuredContent'] as Record<
      string,
      unknown
    >;
    expect(pubResult['isError']).toBe(false);
    expect(typeof pubStructured['key_phrase']).toBe('string');
    const pubWords = (pubStructured['key_phrase'] as string).split(' ');
    expect(pubWords.length).toBe(MNEMONIC_WORDS);
    const pubUrl = pubStructured['url'] as string;
    const pubFragment = pubUrl.split('#')[1] as string;
    const pubKey = parseFragment(pubFragment).key;
    expect(mnemonicToKey(pubWords)).toEqual(pubKey);

    const pubText = JSON.stringify(pubResult['content']);
    expect(pubText).toContain(pubStructured['key_phrase'] as string);
    expect(pubText).toContain(KEY_PHRASE_DISCLOSURE);

    disk.set('/work/doc.md', new TextEncoder().encode('# doc v2\n'));
    const repubResult = await callTool(REPUBLISH_TOOL_NAME, {
      relic_id: pubStructured['relic_id'],
      path: '/work/doc.md',
    });
    const repubStructured = repubResult['structuredContent'] as Record<
      string,
      unknown
    >;
    expect(typeof repubStructured['key_phrase']).toBe('string');
    const repubWords = (repubStructured['key_phrase'] as string).split(' ');
    expect(repubWords.length).toBe(MNEMONIC_WORDS);
    expect(mnemonicToKey(repubWords)).toEqual(pubKey);

    const repubText = JSON.stringify(repubResult['content']);
    expect(repubText).toContain(repubStructured['key_phrase'] as string);
    expect(repubText).toContain(KEY_PHRASE_DISCLOSURE);
  });
});

describe('the state file stays readable in both directions', () => {
  /**
   * The predicate the released client validates an entry with, replicated.
   *
   * A new field is only safe if that build still loads the file: it holds the
   * key and the publish token, so a file it rejects is a file that ends its
   * ability to republish anything. Replicated rather than imported because
   * the point is the shape of the released version, not this one.
   */
  function releasedClientAccepts(entry: unknown): boolean {
    if (entry === null || typeof entry !== 'object' || Array.isArray(entry)) {
      return false;
    }
    const candidate = entry as Record<string, unknown>;
    const source = candidate['source'];
    const sourceOk =
      source === undefined ||
      (source !== null &&
        typeof source === 'object' &&
        !Array.isArray(source) &&
        typeof (source as Record<string, unknown>)['identity'] === 'string' &&
        typeof (source as Record<string, unknown>)['path'] === 'string' &&
        typeof (source as Record<string, unknown>)['description'] === 'string');
    return (
      typeof candidate['key'] === 'string' &&
      typeof candidate['publish_token'] === 'string' &&
      typeof candidate['version'] === 'number' &&
      Number.isSafeInteger(candidate['version']) &&
      (candidate['version'] as number) >= 1 &&
      sourceOk
    );
  }

  test('a file this client writes still loads in the released one', async () => {
    const relicId = await publishFile('shared.md', '# shared\n');
    disk.set('/work/shared.md', new TextEncoder().encode('# shared v2\n'));
    await republish({ relic_id: relicId, path: '/work/shared.md' }, deps);

    const file = JSON.parse(await readFile(publishStatePath(), 'utf8')) as {
      relics: Record<string, Record<string, unknown>>;
    };

    for (const entry of Object.values(file.relics)) {
      expect(releasedClientAccepts(entry)).toBe(true);
    }
    const entry = file.relics[relicId];
    expect(entry?.['filename']).toBe('shared.md');
    expect(typeof entry?.['published_at']).toBe('string');
    expect(typeof entry?.['updated_at']).toBe('string');
    expect(entry?.['version']).toBe(2);
  });

  test('a republish keeps the first publish date and the source', async () => {
    const relicId = await publishFile('dated.md', '# dated\n');
    const before = JSON.parse(await readFile(publishStatePath(), 'utf8')) as {
      relics: Record<string, Record<string, unknown>>;
    };

    now += DAY;
    disk.set('/work/dated.md', new TextEncoder().encode('# dated again\n'));
    await republish({ relic_id: relicId, path: '/work/dated.md' }, deps);

    const after = JSON.parse(await readFile(publishStatePath(), 'utf8')) as {
      relics: Record<string, Record<string, unknown>>;
      sources: Record<string, string>;
    };

    expect(after.relics[relicId]?.['published_at']).toBe(
      before.relics[relicId]?.['published_at']
    );
    // The republish rebuilt the entry from loaded state, which is exactly
    // where an optional field would have been dropped.
    expect(after.relics[relicId]?.['source']).toEqual(
      before.relics[relicId]?.['source']
    );
    expect(Object.values(after.sources)).toContain(relicId);
  });

  test('an unreadable entry is reported, not silently skipped', async () => {
    await publishFile('good.md', '# good\n');
    const path = publishStatePath();
    const file = JSON.parse(await readFile(path, 'utf8')) as {
      relics: Record<string, unknown>;
    };
    file.relics['9damaged9damaged9damaged9d'] = { key: 'only-a-key' };
    await writeFile(path, JSON.stringify(file, null, 2));

    const result = await listRelics({}, deps);

    expect(result.count).toBe(1);
    expect(result.unreadable_entries).toEqual(['9damaged9damaged9damaged9d']);
  });
});
